version: 0.0
os: linux
files:
  - source: puppet/
    destination: /etc/puppet/codedeploy
  - source: target/hello.war
    destination: /var/lib/tomcat6/webapps
hooks:
  BeforeInstall:
    - location: masterless/deploy_hooks/install-puppet.sh
      runas: root
  ApplicationStart:
    - location: masterless/deploy_hooks/puppet-apply.sh
      runas: root
  ValidateService:
    - location: masterless/deploy_hooks/verify_service.sh
      runas: root
