version: 0.0
os: windows
files:
  - source: \ces\files\master.properties
    destination: c:\ces-install
  - source: \ces\files\server.properties
    destination: c:\ces-install
  - source: \ces\application\win-install-tomcat.ps1
    destination: c:\ces-install
  - source: \ces\application\win-install-java.ps1
hooks:
  BeforeInstall:
    - location: ces\installprereqs.ps1
      runas: Administrator
  ApplicationStart:
    - location: ces\deployces.ps1
      runas: Administrator
  ValidateService:
    - location: ces\validateces.ps1
      runas: Administrator
